name: facrm
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  pdf: ^3.11.1
  printing: ^5.13.4
  auto_size_text: 3.0.0
  badges: ^3.1.2
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  cloud_firestore: ^6.1.0
  cloud_firestore_platform_interface: ^7.0.4
  cloud_firestore_web: ^5.1.0
  collection: 1.19.1
  firebase_auth: ^6.0.0
  firebase_auth_platform_interface: ^8.0.0
  firebase_auth_web: ^6.0.0
  firebase_core: ^4.2.1
  firebase_core_platform_interface: ^6.0.2
  firebase_core_web: ^3.3.0
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  google_sign_in_android: ^6.2.1
  google_sign_in_ios: ^5.9.0
  google_sign_in_platform_interface: ^2.5.0
  google_sign_in_web: ^0.12.4+4
  intl: 0.20.2
  json_path: ^0.7.6
  fl_chart: ^0.68.0
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.17
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  percent_indicator: ^4.2.5
  plugin_platform_interface: 2.1.8
  provider: ^6.1.5
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.10
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0
  sqflite: ^2.4.2
  sqflite_common: ^2.5.5
  stream_transform: ^2.1.1
  table_calendar: ^3.2.0
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.16
  url_launcher_ios: ^6.3.3
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.1
  url_launcher_windows: ^3.1.4
  # 골프 플래너 앱 전용 패키지
  flutter_svg: ^2.0.7
  http: ^1.1.0
  audioplayers: ^5.2.1
  # 비밀번호 해싱 (bcrypt)
  bcrypt: ^1.1.3
  # 이메일 발송을 위한 패키지
  mailer: ^6.1.2
  crypto: ^3.0.3
  
  # Supabase (cafe24에서 마이그레이션)
  supabase_flutter: ^2.8.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # 골프 플래너 앱 (서브모듈)
  reservation_system:
    path: ../myxplanner

dependency_overrides:
  http: 1.2.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  image: ^4.5.4
  lints: ^6.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/sounds/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
    # 골프 플래너 앱 assets 추가 (제거됨)
    # - lib/pages/mygolfplanner_app/assets/images/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

